services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    ports:
      - 3005:3000 # for app
      - 5555:5555 # for prisma studio
    command: [ "yarn", "start:dev" ]
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always

volumes:
  backend_node_modules:
