services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    ports:
      - "3000:3000"
    command: [ "yarn", "start:dev" ]
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
